version: '3.8'
services:
  product-service:
    build: ./services/product-service
    image: product-service:latest
    ports:
      - "3001:3000"

  user-service:
    build: ./services/user-service
    image: user-service:latest
    ports:
      - "3002:3000"

  order-service:
    build: ./services/order-service
    image: order-service:latest
    ports:
      - "3003:3000"

  notification-service:
    build: ./services/notification-service
    image: notification-service:latest
    ports:
      - "3004:3000"